INSERT INTO videojuegos (titulo, genero, anio, historia_principal, descripcion, portada) VALUES
('Minecraft', 'Sandbox', 2011, 132, 'Explora mundos generados al azar y construye mientras sobrevives recolectando recursos.', '../img/portadas/1.jpg'),
('Monster Hunter Wilds', 'RPG', 2025, 18, 'Cazadores recorren territorios amplios y enfrentan criaturas enormes en entornos dinámicos.', '../img/portadas/2.jpg'),
('Assassin’s Creed Shadows', 'Acción/Sigilo', 2025, 34, 'Un samurái y una asesina buscan justicia en un Japón feudal lleno de intriga y combates.', '../img/portadas/3.jpg'),
('Black Myth: Wukong', 'Acción', 2024, 38, 'Un guerrero mono lucha contra criaturas míticas y descubre secretos en un mundo fantástico.', '../img/portadas/4.jpg'),
('God of War', 'Acción', 2018, 21, 'Kratos y Atreus recorren tierras nórdicas enfrentando enemigos poderosos y su propio destino.', '../img/portadas/5.jpg'),
('Red Dead Redemption 2', 'Acción', 2018, 50, 'Arthur Morgan enfrenta el declive de su banda mientras lidia con decisiones morales difíciles.', '../img/portadas/6.jpg'),
('Celeste', 'Plataformas', 2018, 8, 'Madeline escala una montaña enfrentando miedos internos y desafiando niveles complejos.', '../img/portadas/7.jpg'),
('Dark Souls III', 'Action RPG', 2016, 32, 'Un mundo oscuro lleno de enemigos implacables donde cada combate exige precisión y paciencia.', '../img/portadas/8.jpg'),
('Bloodborne', 'Action RPG', 2015, 34, 'En Yharnam, un cazador enfrenta horrores mientras descubre una historia inquietante y misteriosa.', '../img/portadas/9.jpg'),
('Sekiro: Shadows Die Twice', 'Acción', 2019, 28, 'Un shinobi lucha por su honor usando bloqueos perfectos y habilidades precisas en un Japón brutal.', '../img/portadas/10.jpg'),
('Cyberpunk 2077', 'RPG', 2020, 24, 'V explora Night City, una urbe vibrante donde decisiones influyen fuertemente en la historia.', '../img/portadas/11.jpg'),
('The Last of Us Part II', 'Acción', 2020, 25, 'Ellie emprende un viaje de venganza marcado por dilemas morales y emociones intensas.', '../img/portadas/12.jpg'),
('Super Mario Odyssey', 'Plataformas', 2017, 12, 'Mario viaja entre reinos variados usando a Cappy para resolver desafíos creativos.', '../img/portadas/13.jpg'),
('Ghost of Tsushima', 'Acción', 2020, 25, 'Jin busca liberar su isla equilibrando honor samurái y tácticas sigilosas.', '../img/portadas/14.jpg'),
('Assassin’s Creed Valhalla', 'Acción', 2020, 60, 'Eivor lidera incursiones vikingas mientras forja alianzas y decide el destino de Inglaterra.', '../img/portadas/15.jpg'),
('Monster Hunter World', 'Action RPG', 2018, 45, 'Caza enormes bestias estudiando sus patrones y mejorando equipo en ecosistemas vivos.', '../img/portadas/16.jpg'),
('Fortnite', 'Battle Royale', 2017, 61, 'Compite contra jugadores construyendo estructuras rápidas y usando habilidades tácticas.', '../img/portadas/17.jpg'),
('League of Legends', 'MOBA', 2009, 1945, 'Equipos de cinco compiten controlando campeones únicos en partidas intensas y estratégicas.', '../img/portadas/18.jpg'),
('GTA V', 'Acción', 2013, 31, 'Tres protagonistas entrelazan historias llenas de golpes, caos urbano y decisiones importantes.', '../img/portadas/19.jpg'),
('Apex Legends', 'Battle Royale', 2019, 105, 'Héroes únicos cooperan en partidas rápidas donde comunicación y precisión son esenciales.', '../img/portadas/20.jpg'),
('Overwatch', 'Shooter', 2016, 323, 'Héroes luchan en equipos coordinados combinando habilidades especiales y estrategia.', '../img/portadas/21.jpg'),
('Persona 5', 'JRPG', 2016, 97, 'Estudiantes roban corazones corruptos mientras equilibran vida escolar y combates por turnos.', '../img/portadas/22.jpg'),
('Metroid Dread', 'Acción', 2021, 9, 'Samus explora un planeta hostil enfrentando robots implacables y secretos de su pasado.', '../img/portadas/23.jpg'),
('The Legend of Zelda: BOTW', 'Aventura', 2017, 50, 'Link despierta en un vasto mundo abierto donde libertad y exploración guían cada paso.', '../img/portadas/24.jpg'),
('Super Smash Bros Ultimate', 'Lucha', 2018, 5, 'Personajes icónicos luchan en escenarios dinámicos con estrategias variadas.', '../img/portadas/25.jpg'),
('Halo Infinite', 'Shooter', 2021, 11, 'Master Chief enfrenta una nueva amenaza en un extenso anillo lleno de combate y exploración.', '../img/portadas/26.jpg'),
('Fire Emblem: Three Houses', 'Estrategia', 2019, 49, 'Dirige estudiantes en batallas tácticas mientras tomas decisiones que afectan la historia.', '../img/portadas/27.jpg'),
('Doom Eternal', 'Shooter', 2020, 15, 'El Doom Slayer enfrenta demonios con combate veloz y mecánicas fluidas intensas.', '../img/portadas/28.jpg'),
('Fall Guys', 'Party', 2020, 54, 'Compite en pruebas caóticas donde coordinación, suerte y reflejos son claves.', '../img/portadas/29.jpg'),
('Hades', 'Roguelike', 2020, 15, 'Zagreus intenta escapar del inframundo enfrentando combates rápidos y diálogos memorables.', '../img/portadas/30.jpg'),
('Stardew Valley', 'Simulación', 2016, 53, 'Administra una granja, construye relaciones y explora cuevas en un entorno relajante.', '../img/portadas/31.jpg'),
('Terraria', 'Sandbox', 2011, 52, 'Excava, construye y lucha en mundos llenos de criaturas donde la exploración es clave.', '../img/portadas/32.jpg'),
('Battlefield 1', 'Shooter', 2016, 6, 'Historias humanas en la Primera Guerra con batallas inmersivas llenas de emoción.', '../img/portadas/33.jpg'),
('Rainbow Six Siege', 'Shooter', 2015, 49, 'Equipos tácticos ejecutan estrategias precisas donde cada operador cumple un rol clave.', '../img/portadas/34.jpg'),
('Valorant', 'Shooter', 2020, 258, 'Agentes con habilidades únicas compiten en duelos tácticos donde precisión es esencial.', '../img/portadas/35.jpg'),
('Genshin Impact', 'RPG', 2020, 25, 'Explora Teyvat con personajes únicos en regiones amplias llenas de magia y secretos.', '../img/portadas/36.jpg'),
('Forza Horizon 5', 'Carreras', 2021, 12, 'Corre por escenarios vibrantes de México con autos detallados y eventos variados.', '../img/portadas/37.jpg'),
('FIFA 23', 'Deportes', 2022, 104, 'Partidos dinámicos recrean fútbol realista donde estrategia influye en cada jugada.', '../img/portadas/38.jpg'),
('NBA 2K23', 'Deportes', 2022, 45, 'Experimenta la NBA con gráficos detallados y modos profundos llenos de intensidad.', '../img/portadas/39.jpg'),
('Rocket League', 'Deportes', 2015, 49, 'Autos con cohetes compiten en partidos vertiginosos donde precisión aérea importa.', '../img/portadas/40.jpg'),
('Dead Cells', 'Roguelike', 2018, 13, 'Explora niveles cambiantes enfrentando enemigos exigentes y mejorando habilidades.', '../img/portadas/41.jpg'),
('Cuphead', 'Plataformas', 2017, 10, 'Combates desafiantes contra jefes animados al estilo clásico de los años treinta.', '../img/portadas/42.jpg'),
('Inside', 'Aventura', 2016, 3, 'Un niño escapa de un mundo oscuro lleno de experimentos inquietantes y misterio.', '../img/portadas/43.jpg'),
('Limbo', 'Aventura', 2010, 3, 'Un universo minimalista oscuro donde cada obstáculo requiere precisión y atención.', '../img/portadas/44.jpg'),
('Ori and the Blind Forest', 'Metroidvania', 2015, 8, 'Ori debe restaurar el bosque enfrentando desafíos acrobáticos y enemigos peligrosos.', '../img/portadas/45.jpg'),
('Ori and the Will of the Wisps', 'Metroidvania', 2020, 10, 'Un viaje conmovedor con plataformas pulidas y combates fluidos en un mundo vivo.', '../img/portadas/46.jpg'),
('Death Stranding', 'Aventura', 2019, 40, 'Sam conecta asentamientos aislados mientras enfrenta criaturas misteriosas.', '../img/portadas/47.jpg'),
('Metal Gear Solid V', 'Acción', 2015, 45, 'Snake dirige operaciones tácticas donde sigilo y estrategia influyen en cada misión.', '../img/portadas/48.jpg'),
('Nier Automata', 'RPG', 2017, 20, 'Androides luchan en guerras existenciales mientras descubren verdades sobre la humanidad.', '../img/portadas/49.jpg'),
('Days Gone', 'Acción', 2019, 36, 'Deacon viaja por un mundo devastado enfrentando hordas y decisiones difíciles.', '../img/portadas/50.jpg'),
('Resident Evil 2 Remake', 'Terror', 2019, 8, 'Leon y Claire sobreviven en Raccoon City enfrentando criaturas letales y tensión.', '../img/portadas/51.jpg'),
('Resident Evil 4 Remake', 'Terror', 2023, 16, 'Leon rescata a Ashley enfrentando amenazas intensas y secretos peligrosos.', '../img/portadas/52.jpg'),
('Silent Hill 2 Remake', 'Terror', 2024, 8, 'James enfrenta horrores psicológicos que revelan verdades perturbadoras.', '../img/portadas/53.jpg'),
('Horizon Zero Dawn', 'Acción', 2017, 22, 'Aloy enfrenta máquinas en un mundo poscolapso lleno de misterios y tecnología.', '../img/portadas/54.jpg'),
('Horizon Forbidden West', 'Acción', 2022, 28, 'Aloy explora nuevas tierras enfrentando amenazas inéditas y secretos antiguos.', '../img/portadas/55.jpg'),
('The Division 2', 'Acción', 2019, 17, 'Agentes luchan por restaurar el orden en Washington D.C. tras un colapso social.', '../img/portadas/56.jpg'),
('Control', 'Acción', 2019, 11, 'Jesse investiga fenómenos paranormales en un edificio lleno de misterios.', '../img/portadas/57.jpg'),
('Returnal', 'Roguelike', 2021, 18, 'Selene queda atrapada en un ciclo temporal enfrentando criaturas alienígenas.', '../img/portadas/58.jpg'),
('Spiderman', 'Acción', 2018, 17, 'Peter Parker protege Nueva York enfrentando villanos y desafíos personales.', '../img/portadas/59.jpg'),
('Spiderman Miles Morales', 'Acción', 2020, 7, 'Miles protege su ciudad con nuevos poderes enfrentando amenazas peligrosas.', '../img/portadas/60.jpg');